### ISSUE TITLE
Just crashing on start

### ISSUE THREAD

**Issue by ndinev** [fasteddy516/SimplySerial#21]
Window 8.1, dot net 4.8. Wemos Mini D1 with latest micropython 1.19

Unhandled Exception: System.Management.ManagementException: This method is not implemented in any class
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.GetMethodParameters(String methodName, ManagementBaseObject& inParameters, IWbe
mClassObjectFreeThreaded& inParametersClass, IWbemClassObjectFreeThreaded& outParametersClass)
   at System.Management.ManagementObject.InvokeMethod(String methodName, Object[] args)
   at SimplySerial.SimplySerial.GetSerialPorts()
   at SimplySerial.SimplySerial.Main(String[] args)

**Comment by fasteddy516** [comment]
My apologies, it looks like some of the new board detection code implemented in version 0.7.0 doesn't play nicely with Windows 8/8.1.   I will update the compatibility notes in the README to reflect this.

You may want to give [v0.6.0](https://github.com/fasteddy516/SimplySerial/releases/tag/v0.6.0) a try.  If you're running MicroPython you won't gain anything from the enhanced CircuitPython detection routines, and I know a number of users running it on Windows 7/8/8.1 with no issues.
